name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  service_locator:
    path: ../service_locator_repository
  get_it: ^7.2.0
  http: ^0.13.5

dev_dependencies:
  very_good_analysis: ^3.1.0
